- name: Run Newman Collection
  run: |
    npx newman run "Collections/E-Commerce API Testing.postman_collection.json" \
    -e "Environment/QA Environment.postman_environment.json" \
    -r cli,htmlextra \
    --reporter-htmlextra-export Reports/API_Report.html